export const posts = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    img: "https://pngimg.com/d/walt_disney_PNG15.png",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    img: "https://pngimg.com/d/emerald_PNG10.png",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
    },
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    emai: "Nathan@yesenia.net",
    img: "https://w7.pngwing.com/pngs/113/493/png-transparent-2018-tesla-model-s-2017-tesla-model-s-tesla-model-3-2018-tesla-model-x-tesla-compact-car-sedan-car-thumbnail.png",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
    },
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    img: "https://pngimg.com/d/tesla_car_PNG59.png",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
    },
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    img: "https://p.kindpng.com/picc/s/125-1250330_tesla-model-tesla-model-3-png-transparent-png.png",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
    },
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    img: "https://freepngimg.com/thumb/final_fantasy/116096-fantasy-final-logo-free-transparent-image-hq-thumb.png",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
    },
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    img: "https://pngimg.com/uploads/star_wars_logo/small/star_wars_logo_PNG9.png",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
    },
  },
];
