export const SHUFFLE_ARRAY = 'SHUFFLE_ARRAY';
export const ADD_RANDOM_THREEDIGITS = 'ADD_RANDOM_THREEDIGITS'
export const CHANGE_NAME_PROPETY = 'CHANGE_NAME_PROPETY'
export const SORT = 'SORT'
export const COUNT_IN_TOTAL = 'COUNT_IN_TOTAL'
