export const INCREMENT_ACTIONS = 'INCREMENT_ACTIONS'
export const SHUFFLE_ARRAY = 'SHUFFLE_ARRAY';
export const ADD_RANDOM_NUMBER = 'ADD_RANDOM_NUMBER';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const SORT_ARRAY = 'SORT_ARRAY';
export const CALCULATE_SUM = 'CALCULATE_SUM'