export {default as Home} from './Home/Home'
export {default as Blog} from './Blog/Blog'
export {default as Posts} from './Posts/Posts'
export {default as Users} from './Users/Users'
export {default as Contact} from './Contact/Contact'
